import argparse
import csv
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt


METHOD_ORDER = ["full", "lora", "adalora", "star_lora"]


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot final_eval_f1 by num_samples for each fine-tuning method."
    )
    parser.add_argument(
        "--input",
        default=Path(__file__).resolve().parent / "datasize_comparison.csv",
        type=Path,
        help="CSV generated by summarize_results.py.",
    )
    parser.add_argument(
        "--output",
        default=Path(__file__).resolve().parent / "datasize_final_eval_f1.png",
        type=Path,
        help="Output image path.",
    )
    parser.add_argument(
        "--log-x",
        action="store_true",
        help="Use a log-scaled x-axis for easier comparison across large sample ranges.",
    )
    return parser.parse_args()


def read_points(csv_path):
    points_by_method = defaultdict(list)

    with csv_path.open(newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file)
        for row in reader:
            if not row.get("num_samples") or not row.get("final_eval_f1"):
                continue

            method = row["method"]
            num_samples = int(row["num_samples"])
            final_eval_f1 = float(row["final_eval_f1"])
            points_by_method[method].append((num_samples, final_eval_f1))

    for points in points_by_method.values():
        points.sort(key=lambda item: item[0])

    return points_by_method


def sorted_methods(points_by_method):
    known_methods = [method for method in METHOD_ORDER if method in points_by_method]
    extra_methods = sorted(set(points_by_method) - set(METHOD_ORDER))
    return known_methods + extra_methods


def plot_final_eval_f1(points_by_method, output_path, log_x=False):
    plt.figure(figsize=(10, 6))

    for method in sorted_methods(points_by_method):
        points = points_by_method[method]
        x_values = [num_samples for num_samples, _ in points]
        y_values = [final_eval_f1 for _, final_eval_f1 in points]
        plt.plot(x_values, y_values, marker="o", linewidth=2, label=method)

    plt.xlabel("num_samples")
    plt.ylabel("final_eval_f1")
    plt.title("Final Evaluation F1 by Training Data Size")
    plt.ylim(0.0, 1.05)
    plt.grid(True, linestyle="--", alpha=0.4)
    plt.legend(title="method")

    if log_x:
        plt.xscale("log")

    plt.tight_layout()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=200)
    plt.close()


def main():
    args = parse_args()
    points_by_method = read_points(args.input)
    if not points_by_method:
        raise SystemExit(f"No plottable rows found in {args.input}")

    plot_final_eval_f1(points_by_method, args.output, log_x=args.log_x)
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
